config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'

  get 'article/:id' => 'articles#show', as: 'article'

  namespace :admin do
    get '' => 'articles#index'
    resources :users
    resources :articles
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #

    user ||= User.new # guest user (not logged in)
    can :manage, :all if user.admin?
    can [:create, :update], Article, user_id: user.id if user.copywriter?

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  is_impressionable
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :title, :body, :image, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles

  after_create :ser_role

  def admin?
    self.has_role? :admin
  end

  def copywriter?
    self.has_role? :copywriter
  end

  def set_role
    self.add_role :copywriter
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base

  protect_from_forgery with: :exception

  before_filter :auth_admin

  layout "admin"

  private

  def auth_admin
    warden.authenticate! scope: :user
    unless current_user.admin? || current_user.copywriter?
      flash[:notice] = "You don't have enough privileges!"
      redirect_to root_path
    end
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::CrudController

  def index
    @q = Article.distinct.search(params[:q])
    @entities = @q.result.page(params[:page]).per(params[:per_page])
  end

  private

  def set_class_name
    @class_name = 'Article'
  end

  def entity_params
    params.require(:article).permit(:title, :body, :image).tap do |param|
      param[:user] = current_user
    end
  end
end

app/controllers/admin/crud_controller.rb
class Admin::CrudController < Admin::AdminController

  before_action :set_class_name
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  def index
    @q = Kernel.const_get(@class_name).search(params[:q])
    @entities = @q.result.page(params[:page]).per(params[:per_page])
  end

  def show
  end

  def new
    @entity = Kernel.const_get(@class_name).new
  end

  def edit
  end

  def create
    @entity = Kernel.const_get(@class_name).new(entity_params)
    if @entity.save
      redirect_to url_for(:action => :index), notice: "#{@class_name} was successfully created."
    else
      render :new
    end
  end

  def update
    if @entity.update(entity_params)
      redirect_to url_for(:action => :index), notice: "#{@class_name} was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @entity.destroy
    redirect_to url_for(:action => :index), notice: "#{@class_name} was successfully deleted."
  end

  private

  def set_class_name
    raise 'method missing'
  end

  def set_entity
    @entity = Kernel.const_get(@class_name).find(params[:id])
  end

  def entity_params
    raise 'method missing'
  end

end

app/controllers/admin/users_controller.rb
Devise::RegistrationsController

class Admin::UsersController < Admin::CrudController

  def authenticate_admin
    redirect_to new_user_session_path unless user_signed_in?
    redirect_to root_path if user_signed_in? && !(current_user.admin?)
  end

  def index
    @q = User.distinct.search(params[:q])
    @entities = @q.result.page(params[:page]).per(params[:per_page])
  end

  def update
    if @entity.update_without_password(entity_params)
      redirect_to admin_user_path(@entity), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_class_name
    @class_name = 'User'
  end

  def entity_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

 impressionist :actions=>[:show]

  def index
    @entities = Article.all.page(params[:page]).per(params[:per_page])
  end

  def show
    @entities = {}
    @entities[:current] = Article.find(params[:id])
    @entities[:recommended] = recommended
  end

  def recommended
    Article.all.sample(2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/articles/_form.html.haml
= simple_form_for [:admin, @entity], html: { class: 'form-horizontal col-sm-offset-2 col-sm-8'} do |f|
  .form-group
    .col-sm-6
      = f.input :title, input_html:{ class: 'form-control'}
  .form-group
    .col-sm-6
      = f.label :image, class: 'control-label'
      = f.file_field :image, class: 'form-control'
  .form-group.col-sm-12
    = f.input :body, as: :summernote, input_html:{ class: 'form-control'}
  .form-group
    .col-sm-6
      = f.button :submit, class: 'btn btn-primary'

app/views/admin/articles/edit.html.haml
.admin-page
  .row
    %h1{:class => 'col-sm-offset-2 col-sm-8'}
      Edit #{@class_name}

  .row
  
    = render 'form'

app/views/admin/articles/index.html.haml
.admin-page.index
  %h1
    #{@class_name}s
    = link_to "Add #{@class_name}", url_for(:action => :new), :class => 'btn btn-primary pull-right '
  .row
    = search_form_for @q, url: url_for(:action => :index) do |f|
      .col-xs-6
        .input-group
          = f.search_field :title_cont, :class=>"form-control", :placeholder => "Search by title"
          %span{:class => "input-group-btn"}
            = f.submit 'Search', :class => "btn btn-default"
  %table{:class => 'table table-striped'}
    %tr
      %th ID
      %th Title
      %th= sort_link @q, :created_at, "Created"
      %th= sort_link @q, :updated_at, "Updated"

      %th

    - @entities.each do |entity|
      - if can? :update, entity
        %tr
          %td= entity.id
          %td= entity.title
          %td= entity.created_at.strftime("%m/%d/%y   %I:%M%p")
          %td= entity.updated_at.strftime("%m/%d/%y   %I:%M%p")
          %td{:class => 'action'}
            = link_to  url_for(:action => :edit, :id => entity.id), :title => "Edit #{@class_name}" do
              %span{:class=>"glyphicon glyphicon-pencil"}
            - if can? :destroy, Article
              = link_to  url_for(:action => :destroy, :id => entity.id), :method => :delete, :data => { :confirm => 'Are you sure?' } , :title => "Remove #{@class_name}" do
                %span{:class=>"glyphicon glyphicon-remove-circle"}

  = paginate @entities, :theme => 'bootstrap'

app/views/admin/articles/new.html.haml
.admin-page
  .row
    %h1{:class => 'col-sm-offset-2 col-sm-8'}
      New #{@class_name}

  .row
    = render 'form'

app/views/admin/general/_form_errors.html.haml
- if object.errors.any?
  .alert.alert-warning
    %button{ :type => "button", :class => "close", 'data-dismiss' => "alert"}
      %span{'aria-hidden' => "true"} ×
      %span{:class => "sr-only"}
        Close
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/admin/users/_form.html.haml
= simple_form_for [:admin, @entity], html: { class: 'form-horizontal col-sm-offset-2 col-sm-6'} do |f|

  = render "admin/general/form_errors",  object:  @entity

  .form-group
    = f.input :email, input_html:{ class: 'form-control'}
  .form-group
    = f.input :password, input_html:{ class: 'form-control'}
  .form-group
    = f.input :password_confirmation, input_html:{ class: 'form-control'}
  .form-group
    = f.button :submit, class: 'btn btn-primary'

app/views/admin/users/edit.html.haml
.admin-page
  .row
    %h1{:class => 'col-sm-offset-2 col-sm-8'}
      Edit #{@class_name}

  .row
    = render 'form'

app/views/admin/users/index.html.haml
.admin-page.index
  %h1
    #{@class_name}s
    - if can? :create, User
      = link_to "Add new copywriter", url_for(:action => :new), :class => 'btn btn-primary pull-right '

  .row
    = search_form_for @q, url: url_for(:action => :index) do |f|
      .col-xs-6
        .input-group
          = f.search_field :email_cont, :class=>"form-control", :placeholder => "Search by Email"
          %span{:class => "input-group-btn"}
            = f.submit 'Search', :class => "btn btn-default"

  %table{:class => 'table table-striped'}
    %tr
      %th ID
      %th Email
      %th= sort_link @q, :last_sign_in_at, "Last Sign In"
      %th= sort_link @q, :created_at, "Created"
      %th= sort_link @q, :updated_at, "Updated"

      %th

    - @entities.each do |entity|
      %tr
        %td= entity.id
        %td= entity.email
        %td= entity.last_sign_in_at.strftime("%m/%d/%y   %I:%M%p") unless  entity.last_sign_in_at.nil?
        %td= entity.created_at.strftime("%m/%d/%y   %I:%M%p")
        %td= entity.updated_at.strftime("%m/%d/%y   %I:%M%p")

        %td{:class => 'action'}
          = link_to  url_for(:action => :show, :id => entity.id), :title => "View #{@class_name}" do
            %span{:class=>"glyphicon glyphicon-eye-open"}

          = link_to  url_for(:action => :edit, :id => entity.id), :title => "Edit #{@class_name}" do
            %span{:class=>"glyphicon glyphicon-pencil"}

          = link_to  url_for(:action => :destroy, :id => entity.id), :method => :delete, :data => { :confirm => 'Are you sure?' } , :title => "Remove #{@class_name}" do
            %span{:class=>"glyphicon glyphicon-remove-circle"}

  = paginate @entities, :theme => 'bootstrap'

app/views/admin/users/new.html.haml
.admin-page
  .row
    %h1{:class => 'col-sm-offset-2 col-sm-8'}
      New #{@class_name}

  .row
    = render 'form'

app/views/admin/users/show.html.haml
.admin-page.show
  .row
    %h1{:class => 'col-sm-offset-3 col-sm-6'}
      = @class_name

  .row
    .col-sm-6.col-sm-offset-3
      %ul
        %li
          %span Email:
          =@entity.email
        %li
          %span Role:
          =@entity.roles_name  
        %li
          %span Updated:
          =@entity.updated_at
        %li
          %span Created:
          =@entity.created_at

app/views/articles/_recommended.haml
%h1
  Random posts
.col-md-12
  - @entities[:recommended].each do |article|
    .col-md-6
      .content-block.blog-post
        .row
          .col-md-12
            = image_tag article.image, class: 'post-attach-img'
            %h2
              = article.title
            .post-content
              = truncate(ActionView::Base.full_sanitizer.sanitize(article.body) , :length => 500, :omission => '...')
              .post-read-more.pull-right
                = link_to  'Read more >>>', article_path(article)

app/views/articles/index.haml
.row
  .col-md-12
    .blog-posts-list
      - @entities.each do |entity|
        .content-block.blog-post
          %h2
            = entity.title
          .row
            .col-md-12
              = image_tag entity.image, class: 'post-attach-img'
              .post-content
                = truncate(ActionView::Base.full_sanitizer.sanitize(entity.body) , :length => 500, :omission => '...')
                .post-read-more.pull-right
                  = link_to  'Read more >>>', article_path(entity)
      = paginate @entities, :theme => 'bootstrap'

app/views/articles/show.haml
.row
  .col-md-12
    .blog-posts-list
      .content-block.blog-post
        %h2
          = @entities[:current].title
        .row
          .col-md-12
            = image_tag @entities[:current].image, class: 'post-attach-img'
            .post-content
              = @entities[:current].body.html_safe
            .post-view-counter
              Viewed #{@entities[:current].impressionist_count(filter: :ip_address)} times
        .line         
        = render 'recommended'

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %title Admin

    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'admin', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    .wrapper
      .header
        .container
          .row
            .col-xs-12
              - if user_signed_in?
                %span.hidden-xs.pull-right
                  Logged in as:
                  %span.name
                    =current_user.email
      .main-menu
        .container
          .row
            %ul
              %li
                =link_to 'Site', root_path
              %li
                - if can? :create, User
                  =link_to 'Users', admin_users_path
              %li
                =link_to 'Articles', admin_articles_path
              %li
                =link_to 'Logout', destroy_user_session_path, method: :delete

      .content
        .container
          -if notice.present?
            .col-md-12.alert.alert-warning
              %button{ :type => "button", :class => "close", 'data-dismiss' => "alert"}
                %span{'aria-hidden' => "true"} ×
                %span{:class => "sr-only"}
                  Close
              = notice
          = yield

      .footer

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MicroBlog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .wrapper
      %header.site-header
        .main-menu
          .container
            .row
              %ul
                %li
                  = link_to 'Home', root_path
                %li
                  = link_to 'item#2', '#'
                %li
                  = link_to 'Admin panel', admin_path
        .site-container
      .site-main
        %div{class: 'content-block'}
          %div{class: 'container'}
            = yield
      %footer.site-footer
        .site-container